language: node_js
node_js: "7"
install: npm i
script: 
 - yarn run build

notifications:
  email: false
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  repo: 'tweetatlas/tweetatlas.github.io'
  local_dir: dist
  on:
    branch: master

